name: TedRegklis
favicon: null
layout_spectrum: 0.3089525776449591
typography_spectrum: 0.602372522233054
title: Ted Regklis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4365382145624608
  lightness: 0.5804839169140905
  saturation: 0.7325810012407601
  rhythmicContrast: 0.15855334885418415
purpose: []
