typography_spectrum: 0.66668
color:
  brandColors:
    - '#efefef'
    - '#0c0c0c'
    - '#6f6f6f'
    - '#444444'
    - '#9e9e9e'
  brandStrength: 1
  lightness: 0
  saturation: 0.9375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.15172
analytics:
  google: null
  facebook: null
  twitter: null
name: TedRegklis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ted Regklis
purpose: []
