name: TedRegklis
favicon: null
layout_spectrum: 0
typography_spectrum: 0.602372522233054
title: Ted Regklis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefef'
    - '#0c0c0c'
    - '#6f6f6f'
    - '#444444'
    - '#9e9e9e'
  brandStrength: 0.5
  lightness: 0.5804839169140905
  saturation: 0.7325810012407601
  rhythmicContrast: 0.15855334885418415
purpose: []
